// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: gradients.proto

package gradients

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DcDmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dm      string `protobuf:"bytes,1,opt,name=dm,proto3" json:"dm,omitempty"`
	Dc      string `protobuf:"bytes,2,opt,name=dc,proto3" json:"dc,omitempty"`
	EpochID string `protobuf:"bytes,3,opt,name=epochID,proto3" json:"epochID,omitempty"`
}

func (x *DcDmRequest) Reset() {
	*x = DcDmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradients_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DcDmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DcDmRequest) ProtoMessage() {}

func (x *DcDmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gradients_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DcDmRequest.ProtoReflect.Descriptor instead.
func (*DcDmRequest) Descriptor() ([]byte, []int) {
	return file_gradients_proto_rawDescGZIP(), []int{0}
}

func (x *DcDmRequest) GetDm() string {
	if x != nil {
		return x.Dm
	}
	return ""
}

func (x *DcDmRequest) GetDc() string {
	if x != nil {
		return x.Dc
	}
	return ""
}

func (x *DcDmRequest) GetEpochID() string {
	if x != nil {
		return x.EpochID
	}
	return ""
}

type DcDmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weights string `protobuf:"bytes,1,opt,name=weights,proto3" json:"weights,omitempty"`
	Bias    string `protobuf:"bytes,2,opt,name=bias,proto3" json:"bias,omitempty"`
	Com     string `protobuf:"bytes,3,opt,name=com,proto3" json:"com,omitempty"`
}

func (x *DcDmReply) Reset() {
	*x = DcDmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradients_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DcDmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DcDmReply) ProtoMessage() {}

func (x *DcDmReply) ProtoReflect() protoreflect.Message {
	mi := &file_gradients_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DcDmReply.ProtoReflect.Descriptor instead.
func (*DcDmReply) Descriptor() ([]byte, []int) {
	return file_gradients_proto_rawDescGZIP(), []int{1}
}

func (x *DcDmReply) GetWeights() string {
	if x != nil {
		return x.Weights
	}
	return ""
}

func (x *DcDmReply) GetBias() string {
	if x != nil {
		return x.Bias
	}
	return ""
}

func (x *DcDmReply) GetCom() string {
	if x != nil {
		return x.Com
	}
	return ""
}

type EpochIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochID string `protobuf:"bytes,1,opt,name=epochID,proto3" json:"epochID,omitempty"`
}

func (x *EpochIDRequest) Reset() {
	*x = EpochIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradients_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpochIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochIDRequest) ProtoMessage() {}

func (x *EpochIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gradients_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochIDRequest.ProtoReflect.Descriptor instead.
func (*EpochIDRequest) Descriptor() ([]byte, []int) {
	return file_gradients_proto_rawDescGZIP(), []int{2}
}

func (x *EpochIDRequest) GetEpochID() string {
	if x != nil {
		return x.EpochID
	}
	return ""
}

type EpochIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EpochIDReply) Reset() {
	*x = EpochIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradients_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpochIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochIDReply) ProtoMessage() {}

func (x *EpochIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_gradients_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochIDReply.ProtoReflect.Descriptor instead.
func (*EpochIDReply) Descriptor() ([]byte, []int) {
	return file_gradients_proto_rawDescGZIP(), []int{3}
}

func (x *EpochIDReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gradients_proto protoreflect.FileDescriptor

var file_gradients_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x0b,
	0x44, 0x63, 0x44, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x49, 0x44, 0x22, 0x4b, 0x0a, 0x09, 0x44, 0x63, 0x44, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x69, 0x61, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63,
	0x6f, 0x6d, 0x22, 0x2a, 0x0a, 0x0e, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x44, 0x22, 0x28,
	0x0a, 0x0c, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x93, 0x01, 0x0a, 0x09, 0x47, 0x72, 0x61,
	0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x63,
	0x44, 0x6d, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44,
	0x63, 0x44, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x61,
	0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x63, 0x44, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x4a, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42,
	0x79, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x44, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x61, 0x64, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x45, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x58,
	0x0a, 0x1a, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2e, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x0e, 0x47, 0x72,
	0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x28,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x67,
	0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gradients_proto_rawDescOnce sync.Once
	file_gradients_proto_rawDescData = file_gradients_proto_rawDesc
)

func file_gradients_proto_rawDescGZIP() []byte {
	file_gradients_proto_rawDescOnce.Do(func() {
		file_gradients_proto_rawDescData = protoimpl.X.CompressGZIP(file_gradients_proto_rawDescData)
	})
	return file_gradients_proto_rawDescData
}

var file_gradients_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gradients_proto_goTypes = []interface{}{
	(*DcDmRequest)(nil),    // 0: gradients.DcDmRequest
	(*DcDmReply)(nil),      // 1: gradients.DcDmReply
	(*EpochIDRequest)(nil), // 2: gradients.EpochIDRequest
	(*EpochIDReply)(nil),   // 3: gradients.EpochIDReply
}
var file_gradients_proto_depIdxs = []int32{
	0, // 0: gradients.Gradients.SendDcDm:input_type -> gradients.DcDmRequest
	2, // 1: gradients.Gradients.SendQueryByEpochID:input_type -> gradients.EpochIDRequest
	1, // 2: gradients.Gradients.SendDcDm:output_type -> gradients.DcDmReply
	3, // 3: gradients.Gradients.SendQueryByEpochID:output_type -> gradients.EpochIDReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gradients_proto_init() }
func file_gradients_proto_init() {
	if File_gradients_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gradients_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DcDmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradients_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DcDmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradients_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpochIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradients_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpochIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gradients_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gradients_proto_goTypes,
		DependencyIndexes: file_gradients_proto_depIdxs,
		MessageInfos:      file_gradients_proto_msgTypes,
	}.Build()
	File_gradients_proto = out.File
	file_gradients_proto_rawDesc = nil
	file_gradients_proto_goTypes = nil
	file_gradients_proto_depIdxs = nil
}
